/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distance_converter;

import javax.swing.JOptionPane;

/**
 *
 * @author Hannah
 */
public class distance_converter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(distance_converter.class.getName());

    /**
     * Creates new form distance_converter
     */
    public distance_converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        covertbtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        txtFormula = new javax.swing.JTextField();
        result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Convert From Miles to Kilometers");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an option", "Miles to Nautical Miles", "Nautical Miles to Miles", "Miles to Km", "Km to Miles" }));
        jPanel1.add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 210, -1));

        jLabel2.setText("Enter Mileage");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 106, 150, 30));

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        covertbtn.setText("Convert");
        covertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                covertbtnActionPerformed(evt);
            }
        });
        jPanel1.add(covertbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));
        jPanel1.add(txtFormula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 250, -1));

        result.setText("Result Here");
        jPanel1.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        t1.setText("");
        txtFormula.setText("");
        result.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void covertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_covertbtnActionPerformed
        if(combo1.getSelectedItem().equals("Select an option") || t1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You must select an option and insert the values", "Error Message",JOptionPane.INFORMATION_MESSAGE);
        }else if(combo1.getSelectedItem().equals("Miles to Nautical Miles"))
        { 
            double miles = Double.parseDouble(t1.getText());
            double nautical_miles = miles/1.15078;
            String value = String.format("%.2f", nautical_miles);
            result.setText(value);
            txtFormula.setText("nautical miles = miles/1.15078");
        }else if(combo1.getSelectedItem().equals("Nautical Miles to Miles"))
        { 
            double nautical_miles = Double.parseDouble(t1.getText());
            double miles = nautical_miles*1.15078;
            String value = String.format("%.2f", miles);
            result.setText(value);
            txtFormula.setText("miles = nautical_miles*1.15078");
        }else if(combo1.getSelectedItem().equals("Miles to Km"))
        { 
            double miles = Double.parseDouble(t1.getText());
            double km = miles*1.609344;
            String value = String.format("%.2f", km);
            result.setText(value);
            txtFormula.setText("KM = miles*1.609344");
        }else if(combo1.getSelectedItem().equals("Km to Miles"))
        { 
            double km = Double.parseDouble(t1.getText());
            double miles = km/1.609344;
            String value = String.format("%.2f", miles);
            result.setText(value);
            txtFormula.setText("miles = km/1.609344");
        }
    }//GEN-LAST:event_covertbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new distance_converter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JButton covertbtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel result;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField txtFormula;
    // End of variables declaration//GEN-END:variables
}
