/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package currency_converter;

import javax.swing.JOptionPane;

/**
 *
 * @author Hannah
 */
public class currency_converter extends javax.swing.JFrame {
    
    String[] currencyUnits = {
        "units",
        "US Dollar",
        "Nigerian Naira",
        "Brazillian Real",
        "Canadian Dollar",
        "Kenyan Shilling",
        "Indonesian Rupiah",
        "Indian Rupee",
        "Philippine Peso",
        "Pakistani Rupee",
    };
    
    double US_Dollar = 1.31;
    double Nigerian_Naira = 476.57;
    double Brazillian_Real = 5.47;
    double Canadian_Dollar = 1.71;
    double Kenyan_Shilling = 132.53;
    double Indonesian_Rupiah = 19554.94;
    double Indian_Rupee = 95.21;
    double Philippine_Peso = 71.17;
    double Pakistani_Rupee = 162.74;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(currency_converter.class.getName());

    /**
     * Creates new form currency_converter
     */
    public currency_converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        secondCountry = new javax.swing.JComboBox<>();
        firstCountry = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstCurrencyUnit = new javax.swing.JLabel();
        ResetBtn = new javax.swing.JButton();
        convertBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        secondCurrencyUnit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Currency Converter");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 22, -1, -1));

        secondCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "USA", "Nigeria", "Brazil", "Canada", "Kenya", "Indonesia", "India", "Philippine", "Pakistan" }));
        secondCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                secondCountryItemStateChanged(evt);
            }
        });
        jPanel1.add(secondCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 87, 198, 40));

        firstCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "USA", "Nigeria", "Brazil", "Canada", "Kenya", "Indonesia", "India", "Philippine", "Pakistan" }));
        firstCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                firstCountryItemStateChanged(evt);
            }
        });
        jPanel1.add(firstCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 87, 197, 40));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 133, 197, 38));
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 133, 198, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("From currency of");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 65, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("To currency of");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 65, -1, -1));

        firstCurrencyUnit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        firstCurrencyUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstCurrencyUnit.setText("units");
        jPanel1.add(firstCurrencyUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 190, 190, -1));

        ResetBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        convertBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        convertBtn.setText("Convert Currency");
        convertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertBtnActionPerformed(evt);
            }
        });
        jPanel1.add(convertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 223, -1, -1));

        ExitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 130, -1));

        secondCurrencyUnit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        secondCurrencyUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        secondCurrencyUnit.setText("units");
        jPanel1.add(secondCurrencyUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 190, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        t1.setText("");
        t2.setText("");
        firstCurrencyUnit.setText("units");
        secondCurrencyUnit.setText("units");
        
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void firstCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_firstCountryItemStateChanged
        
        int position = firstCountry.getSelectedIndex();
        firstCurrencyUnit.setText(currencyUnits[position]);
    }//GEN-LAST:event_firstCountryItemStateChanged

    private void secondCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_secondCountryItemStateChanged
       
        int position = secondCountry.getSelectedIndex();
        secondCurrencyUnit.setText(currencyUnits[position]);
    }//GEN-LAST:event_secondCountryItemStateChanged

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void convertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBtnActionPerformed
        if(firstCountry.getSelectedIndex() == 0 || secondCountry.getSelectedIndex() == 0 || t1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must select an option and insert the values", "Error Message",JOptionPane.INFORMATION_MESSAGE);
        }
        
        double amountToChange = Double.parseDouble(t1.getText());
        double amountInPounds = 0.0;
        double amountChanged = 0.0;
        
        switch(firstCountry.getSelectedItem().toString()){
            case "USA": amountInPounds = amountToChange / US_Dollar;break; 
            case "Nigeria": amountInPounds = amountToChange / Nigerian_Naira;break; 
            case "Brazil": amountInPounds = amountToChange / Brazillian_Real;break; 
            case "Canada": amountInPounds = amountToChange / Canadian_Dollar;break; 
            case "Kenya": amountInPounds = amountToChange / Kenyan_Shilling;break; 
            case "Indonesia": amountInPounds = amountToChange / Indonesian_Rupiah;break;
            case "India": amountInPounds = amountToChange / Indian_Rupee;break; 
            case "Philippine": amountInPounds = amountToChange / Philippine_Peso;break; 
            case "Pakistan": amountInPounds = amountToChange / Pakistani_Rupee;break; 
            default:amountInPounds = 0.0;
        }
        
        switch(secondCountry.getSelectedItem().toString()){
            case "India": amountChanged = amountInPounds * Indian_Rupee;break; 
            case "USA": amountChanged = amountInPounds * US_Dollar;break; 
            case "Nigeria": amountChanged = amountInPounds * Nigerian_Naira;break; 
            case "Brazil": amountChanged = amountInPounds * Brazillian_Real;break; 
            case "Canada": amountChanged = amountInPounds * Canadian_Dollar;break; 
            case "Kenya": amountChanged = amountInPounds * Kenyan_Shilling;break; 
            case "Indonesia": amountChanged = amountInPounds * Indonesian_Rupiah;break;
            case "Philippine": amountChanged = amountInPounds * Philippine_Peso;break; 
            case "Pakistan": amountChanged = amountInPounds * Pakistani_Rupee;break; 
            default:amountChanged = amountInPounds * 0.0;
        }
        
        String value = String.format("%.2f", amountChanged);
        t2.setText(value);
    }//GEN-LAST:event_convertBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new currency_converter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton convertBtn;
    private javax.swing.JComboBox<String> firstCountry;
    private javax.swing.JLabel firstCurrencyUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> secondCountry;
    private javax.swing.JLabel secondCurrencyUnit;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
